meta_product_name: "Rookstars"
meta_title: "Rookstars - Lifting tech graduates and NGOs to digital success"
meta_description: "Rookstars is a platform that connects LeWagon alumni with NGOs looking to enhance their digital brand; it turns programming rookies into tech stars. Helping others is how we help ourselves."
meta_image: "meta.jpg"
meta_type: "website"
meta_url: "www.rookstars.eu"

